-- CommuteIT Supabase demo setup
-- Run this in Supabase SQL Editor AFTER enabling Anonymous Sign-Ins:
-- Authentication > Providers > Anonymous Sign-Ins > Enable
--
-- The demo uses signInAnonymously(), so no real email/password is required.
-- Each demo login receives a fresh authenticated user. On logout the frontend
-- deletes that user's saved routes, trips, and profile rows, then signs out.

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  first_name text not null default 'Drei',
  last_name text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Safe migration for existing CommuteIT databases whose profiles table was
-- created before the editable-name fields were added.
alter table public.profiles
  add column if not exists first_name text;
alter table public.profiles
  add column if not exists last_name text;
alter table public.profiles
  alter column first_name set default 'Commuter';
alter table public.profiles
  alter column last_name set default '';


create table if not exists public.saved_routes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  from_location text not null,
  to_location text not null,
  mode text not null,
  distance_km numeric not null default 0,
  duration_min integer not null default 0,
  fare numeric not null default 0,
  co2 numeric not null default 0,
  eco_score integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  from_location text not null,
  to_location text not null,
  mode text not null,
  distance_km numeric not null default 0,
  duration_min integer not null default 0,
  fare numeric not null default 0,
  co2 numeric not null default 0,
  eco_score integer not null default 0,
  summary text,
  occurred_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.saved_routes enable row level security;
alter table public.trips enable row level security;

-- Re-runnable policies.
drop policy if exists "Users can read their own profile" on public.profiles;
drop policy if exists "Users can insert their own profile" on public.profiles;
drop policy if exists "Users can update their own profile" on public.profiles;
drop policy if exists "Users can delete their own profile" on public.profiles;

create policy "Users can read their own profile" on public.profiles
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can insert their own profile" on public.profiles
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users can update their own profile" on public.profiles
  for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users can delete their own profile" on public.profiles
  for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "Users can read their own saved routes" on public.saved_routes;
drop policy if exists "Users can insert their own saved routes" on public.saved_routes;
drop policy if exists "Users can update their own saved routes" on public.saved_routes;
drop policy if exists "Users can delete their own saved routes" on public.saved_routes;

create policy "Users can read their own saved routes" on public.saved_routes
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can insert their own saved routes" on public.saved_routes
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users can update their own saved routes" on public.saved_routes
  for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users can delete their own saved routes" on public.saved_routes
  for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "Users can read their own trips" on public.trips;
drop policy if exists "Users can insert their own trips" on public.trips;
drop policy if exists "Users can update their own trips" on public.trips;
drop policy if exists "Users can delete their own trips" on public.trips;

create policy "Users can read their own trips" on public.trips
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can insert their own trips" on public.trips
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users can update their own trips" on public.trips
  for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users can delete their own trips" on public.trips
  for delete to authenticated using ((select auth.uid()) = user_id);

create index if not exists saved_routes_user_id_idx on public.saved_routes(user_id);
create index if not exists trips_user_id_idx on public.trips(user_id);

-- Helpful: allow the Data API roles to reach the tables; RLS still controls rows.
grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.saved_routes to authenticated;
grant select, insert, update, delete on public.trips to authenticated;
grant usage, select on all sequences in schema public to authenticated;


-- Enable Supabase Realtime for per-user live dashboard counters.
-- RLS continues to control which rows each authenticated user can read.
alter table public.trips replica identity full;
alter table public.saved_routes replica identity full;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='trips') then
      alter publication supabase_realtime add table public.trips;
    end if;
    if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='saved_routes') then
      alter publication supabase_realtime add table public.saved_routes;
    end if;
  end if;
end $$;

-- Optional community carpool matching and aggregated planning insights.
create table if not exists public.carpool_posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  from_location text not null,
  to_location text not null,
  departure_at timestamptz not null,
  seats integer not null default 1 check (seats between 1 and 6),
  created_at timestamptz not null default now()
);

alter table public.carpool_posts enable row level security;
drop policy if exists "Authenticated users can read active carpool posts" on public.carpool_posts;
drop policy if exists "Users can insert their own carpool posts" on public.carpool_posts;
drop policy if exists "Users can update their own carpool posts" on public.carpool_posts;
drop policy if exists "Users can delete their own carpool posts" on public.carpool_posts;
create policy "Authenticated users can read active carpool posts" on public.carpool_posts
  for select to authenticated using (departure_at >= now());
create policy "Users can insert their own carpool posts" on public.carpool_posts
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users can update their own carpool posts" on public.carpool_posts
  for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Users can delete their own carpool posts" on public.carpool_posts
  for delete to authenticated using ((select auth.uid()) = user_id);
grant select, insert, update, delete on public.carpool_posts to authenticated;
grant usage, select on sequence public.carpool_posts_id_seq to authenticated;

-- Secure aggregate function: returns route-level statistics only, never user IDs.
create or replace function public.get_public_route_stats()
returns table(route text, trip_count bigint, avg_distance numeric, avg_duration numeric, avg_co2 numeric)
language sql
security definer
set search_path = public
as $$
  select
    concat(from_location, ' → ', to_location) as route,
    count(*) as trip_count,
    round(avg(distance_km), 2) as avg_distance,
    round(avg(duration_min), 1) as avg_duration,
    round(avg(co2), 2) as avg_co2
  from public.trips
  group by from_location, to_location
  order by count(*) desc
  limit 10;
$$;
revoke all on function public.get_public_route_stats() from public;
grant execute on function public.get_public_route_stats() to authenticated;

-- Recommendation feedback for future accuracy analysis.
alter table public.trips add column if not exists recommendation_feedback smallint;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='carpool_posts') then
      alter publication supabase_realtime add table public.carpool_posts;
    end if;
  end if;
end $$;

-- Profile names are editable by the signed-in account owner.
-- Existing accounts can use the Settings > Change your name option without
-- needing a new account; the frontend upserts the profile row on save.


-- Registered account profile bootstrap for editable CommuteIT names.
-- Anonymous/demo users are intentionally excluded.
create or replace function public.handle_new_commuteit_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(new.is_anonymous, false) then
    return new;
  end if;

  insert into public.profiles (user_id, first_name, last_name)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'first_name', ''), split_part(coalesce(new.email, 'Commuter'), '@', 1)),
    coalesce(new.raw_user_meta_data ->> 'last_name', '')
  )
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created_commuteit on auth.users;
create trigger on_auth_user_created_commuteit
after insert on auth.users
for each row execute function public.handle_new_commuteit_user();

-- Backfill profile rows for existing registered accounts.
insert into public.profiles (user_id, first_name, last_name)
select
  u.id,
  coalesce(nullif(u.raw_user_meta_data ->> 'first_name', ''), split_part(coalesce(u.email, 'Commuter'), '@', 1)),
  coalesce(u.raw_user_meta_data ->> 'last_name', '')
from auth.users u
where coalesce(u.is_anonymous, false) = false
  and not exists (select 1 from public.profiles p where p.user_id = u.id);
